### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by keilw** [razem-io/JBakeUI#3]
Just downloaded the latest codebase. Building with Gradle works, but either "gradle run" or executing the resulting JBakeUI.bat both cause the following error:

Exception in thread "main" java.awt.IllegalComponentStateException: contentPane cannot be set to null.
        at javax.swing.JRootPane.setContentPane(Unknown Source)
        at javax.swing.JFrame.setContentPane(Unknown Source)
        at com.jbake.ui.Frontend.init(Frontend.java:103)
        at com.jbake.ui.Frontend.<init>(Frontend.java:39)
        at com.jbake.ui.Frontend.main(Frontend.java:306)

**Comment by razem-io** [comment]
That's due to the reason that I used the IntelliJ Grid Layout. I will
commit a new version this weekend which uses JavaFX instead. This should
solve the issue. Currently IntelliJ is needed in order compile and run.
Am 06.03.2015 20:59 schrieb "Werner Keil" notifications@github.com:

**Comment by keilw** [comment]
So you'll completely rewrite it from Swing to JavaFX? Well for relatively small Ui that sounds OK. Better than dependencies to closed/proprietary (even if partly free) apps like IntelliJ;-)

**Comment by razem-io** [comment]
Yep that is the plan (https://github.com/razem-io/JBakeUI/issues/2) :). It shouldn't be too much work, since most of the methods needed by Jabke UI, are already outside of the Swing classes. I agree that using closed/proprietary dependencies is not the way to go. I often use them for rapid prototyping because of the ease of use.

**Comment by razem-io** [comment]
Should be fixed by https://github.com/razem-io/JBakeUI/commit/77fe3f5c281fcc6a2884020e20884e2f51b58102. If you could confirm on your side it would be great!
